name: CD (Deploy VitePress site to Pages)

on: # zizmor: ignore[dangerous-triggers]
  # region triggers
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
  # endregion triggers
  workflow_dispatch:

permissions: {}

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  check:
    name: Deploy pre check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    outputs:
      result: ${{ steps.gen_output.outputs.result }}

    steps:
      - id: gen_output
        # region condition
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        # endregion condition
        run: |
          echo "result=true" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: ${{ needs.check.outputs.result }}

    needs:
      - check

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@6735bb9dd019900ebc16ce34e13c118b3917d1f7 # v1.2.0

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Build with VitePress
        run: pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: docs/.vitepress/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    needs:
      - check
      - build

    if: ${{ needs.check.outputs.result }}

    permissions:
      contents: read
      pages: write # required to deploy to GitHub Pages
      id-token: write # required for OIDC authentication with GitHub Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  failure:
    name: Failure
    runs-on: ubuntu-latest
    timeout-minutes: 1

    if: ${{ !needs.check.outputs.result }}

    needs:
      - check

    steps:
      - run: echo 'CI failed. Deploy won't be executed'
