name: CD (Deploy VitePress site to Pages)

# region triggers
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

  workflow_dispatch:
# endregion triggers

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  check:
    name: Deploy pre check
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.gen_output.outputs.result }}
    steps:
      - id: gen_output
        # region condition
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        # endregion condition
        run: |
          echo "result=true" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    needs: [check]
    if: ${{ needs.check.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with VitePress
        run: pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    name: Deploy
    needs: [check, build]
    if: ${{ needs.check.outputs.result }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  failure:
    name: "Failure"
    runs-on: ubuntu-latest
    needs: [check]
    if: ${{ !needs.check.outputs.result }}
    steps:
      - run: echo 'CI failed. Deploy won't be executed'
