name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    name: Run all checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@d5a5561c7caea4f18642f3967aad095af51c3905 # v2.1.0

      - name: Build
        run: pnpm run docs:build

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Spellcheck
        run: pnpm run spellcheck

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
